/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type StandardErrorData = {
  message: string;
};

export class StandardError extends Error {
  /** The original data that was passed to this error instance. */
  data$: StandardErrorData;

  constructor(err: StandardErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "StandardError";
  }
}

/** @internal */
export const StandardError$inboundSchema: z.ZodType<
  StandardError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new StandardError(v);
  });

/** @internal */
export type StandardError$Outbound = {
  message: string;
};

/** @internal */
export const StandardError$outboundSchema: z.ZodType<
  StandardError$Outbound,
  z.ZodTypeDef,
  StandardError
> = z.instanceof(StandardError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StandardError$ {
  /** @deprecated use `StandardError$inboundSchema` instead. */
  export const inboundSchema = StandardError$inboundSchema;
  /** @deprecated use `StandardError$outboundSchema` instead. */
  export const outboundSchema = StandardError$outboundSchema;
  /** @deprecated use `StandardError$Outbound` instead. */
  export type Outbound = StandardError$Outbound;
}
