/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Testimonials } from "./testimonials.js";

export class Testify extends ClientSDK {
  private _testimonials?: Testimonials;
  get testimonials(): Testimonials {
    return (this._testimonials ??= new Testimonials(this._options));
  }
}
