/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testimonialsCreate } from "../funcs/testimonialsCreate.js";
import { testimonialsGet } from "../funcs/testimonialsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Testimonials extends ClientSDK {
  async get(
    request: operations.GetApiTestimonialsRequest,
    options?: RequestOptions,
  ): Promise<components.TestimonialsResponse> {
    return unwrapAsync(testimonialsGet(
      this,
      request,
      options,
    ));
  }

  async create(
    request: operations.PostApiTestimonialsSpaceIdRequest,
    options?: RequestOptions,
  ): Promise<components.Testimonial> {
    return unwrapAsync(testimonialsCreate(
      this,
      request,
      options,
    ));
  }
}
