/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the @trytestify/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx testimonialsGet.ts
 */

import { Testify } from "@trytestify/sdk";

const testify = new Testify();

async function main() {
  const result = await testify.get({
    spaceId: "<id>",
  });

  console.log(result);
}

main().catch(console.error);
