/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiTestimonialsRequest = {
  spaceId: string;
};

/** @internal */
export const GetApiTestimonialsRequest$inboundSchema: z.ZodType<
  GetApiTestimonialsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  spaceId: z.string(),
});

/** @internal */
export type GetApiTestimonialsRequest$Outbound = {
  spaceId: string;
};

/** @internal */
export const GetApiTestimonialsRequest$outboundSchema: z.ZodType<
  GetApiTestimonialsRequest$Outbound,
  z.ZodTypeDef,
  GetApiTestimonialsRequest
> = z.object({
  spaceId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiTestimonialsRequest$ {
  /** @deprecated use `GetApiTestimonialsRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiTestimonialsRequest$inboundSchema;
  /** @deprecated use `GetApiTestimonialsRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiTestimonialsRequest$outboundSchema;
  /** @deprecated use `GetApiTestimonialsRequest$Outbound` instead. */
  export type Outbound = GetApiTestimonialsRequest$Outbound;
}

export function getApiTestimonialsRequestToJSON(
  getApiTestimonialsRequest: GetApiTestimonialsRequest,
): string {
  return JSON.stringify(
    GetApiTestimonialsRequest$outboundSchema.parse(getApiTestimonialsRequest),
  );
}

export function getApiTestimonialsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiTestimonialsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiTestimonialsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiTestimonialsRequest' from JSON`,
  );
}
