/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTestimonialsSpaceIdRequest = {
  spaceId: string;
  /**
   * Data for the new testimonial.
   */
  createTestimonialPayload: components.CreateTestimonialPayload;
};

/** @internal */
export const PostApiTestimonialsSpaceIdRequest$inboundSchema: z.ZodType<
  PostApiTestimonialsSpaceIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  spaceId: z.string(),
  CreateTestimonialPayload: components.CreateTestimonialPayload$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "CreateTestimonialPayload": "createTestimonialPayload",
  });
});

/** @internal */
export type PostApiTestimonialsSpaceIdRequest$Outbound = {
  spaceId: string;
  CreateTestimonialPayload: components.CreateTestimonialPayload$Outbound;
};

/** @internal */
export const PostApiTestimonialsSpaceIdRequest$outboundSchema: z.ZodType<
  PostApiTestimonialsSpaceIdRequest$Outbound,
  z.ZodTypeDef,
  PostApiTestimonialsSpaceIdRequest
> = z.object({
  spaceId: z.string(),
  createTestimonialPayload: components.CreateTestimonialPayload$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createTestimonialPayload: "CreateTestimonialPayload",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiTestimonialsSpaceIdRequest$ {
  /** @deprecated use `PostApiTestimonialsSpaceIdRequest$inboundSchema` instead. */
  export const inboundSchema = PostApiTestimonialsSpaceIdRequest$inboundSchema;
  /** @deprecated use `PostApiTestimonialsSpaceIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostApiTestimonialsSpaceIdRequest$outboundSchema;
  /** @deprecated use `PostApiTestimonialsSpaceIdRequest$Outbound` instead. */
  export type Outbound = PostApiTestimonialsSpaceIdRequest$Outbound;
}

export function postApiTestimonialsSpaceIdRequestToJSON(
  postApiTestimonialsSpaceIdRequest: PostApiTestimonialsSpaceIdRequest,
): string {
  return JSON.stringify(
    PostApiTestimonialsSpaceIdRequest$outboundSchema.parse(
      postApiTestimonialsSpaceIdRequest,
    ),
  );
}

export function postApiTestimonialsSpaceIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTestimonialsSpaceIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTestimonialsSpaceIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTestimonialsSpaceIdRequest' from JSON`,
  );
}
